### ISSUE TITLE
Importing DAE

### ISSUE THREAD

**Issue by chaze117** [gdkchan/SPICA#1]
Hi I exported Bulbasaur with all animations it's nearly 21 MB, but when I import it to blender the animations are not imported. If I export it to FBX no animation and about 1,5 MB. 
What might be the problem?  Or just the blender importer can't handle the animations? 
Thank you for the answer.

**Comment by gdkchan** [comment]
it uses animation clips to export all animations to the same dae file but looks like pretty much no software supports it which is a shame so the only solution is exporting each animation on a separate dae file.

**Comment by chaze117** [comment]
Thank you
