### ISSUE TITLE
Exported armatures in SMD aren't properly rigged

### ISSUE THREAD

**Issue by jugolm** [gdkchan/SPICA#10]
Which is weird because the SMD exporter worked fine in Ohana3DS

Attached a screenshot for comparison (Mega Rayquaza from Sun/Moon, exported by both apps)

![image](https://cloud.githubusercontent.com/assets/20032942/26016380/23077e4c-373b-11e7-833e-0f18908ae7a9.png)

EDIT: Seems like the mesh triangles are assigned to the wrong bone:
![image](https://cloud.githubusercontent.com/assets/20032942/26018335/9a245eba-3744-11e7-993d-dc46b7890a87.png)

**Comment by gdkchan** [comment]
Just to be sure, is the problem fixed now?

**Comment by jugolm** [comment]
Yes, it's fixed, thanks!

Forgot to mention another problem (smd for animations exports an empty file), but I guess I should submit a separate issue.

![image](https://cloud.githubusercontent.com/assets/20032942/26029426/2adce5fa-380b-11e7-9aa2-a9ae41e20b69.png)

**Comment by gdkchan** [comment]
Yes, it's a separate issue, you can open it if you want. It's because I didn't implemented SMD animation support yet.
