### ISSUE TITLE
Can't open bch of this game

### ISSUE THREAD

**Issue by Aper99** [gdkchan/SPICA#14]
I've been trying to open bch files of this game, Aikatsu No.1 Stage, but it says that the file format is  unsupported.
I was able to open it on ohana rebirth.
Here is a file for test it.
<a href="http://www81.zippyshare.com/v/PF7c6kTT/file.html" target="_blank" class="zippyshare_link">cos104_1004_T.zip</a>

**Comment by gdkchan** [comment]
It doesnt open because the file is compressed with LZSS compression. You need to decompress the model first to open with SPICA. Ohana decompresses the model automatically.

**Comment by Aper99** [comment]
Thank you. Now the files open
