### ISSUE TITLE
Compiled version doesn't works,

### ISSUE THREAD

**Issue by luisdaniel10** [gdkchan/SPICA#16]
hi!, when i open the compiled version that u put to download, when i try to open a file a error coming, 
''cant load type 'System.Numerics.Matrix4x4'

**Comment by gdkchan** [comment]
You need .net framework 4.6.2 to run it. Older versions (before 4.6) didn't have the System.Numerics.Vectors types.

**Comment by gdkchan** [comment]
Well I guess that updating .net framework version fixed the issue, so closing this...
