### ISSUE TITLE
Tangent is wrong in fragment shader

### ISSUE THREAD

**Issue by freedom12** [gdkchan/SPICA#2]
![rtx](https://cloud.githubusercontent.com/assets/5900461/21219347/6205b994-c2ef-11e6-9920-83bb3063f120.png)
Sorry，my English is poor
I think the value of tangent is not right in fragment shader

**Comment by gdkchan** [comment]
Hmm... Are you sure it is wrong? I don't think that tangents are supposed to be smooth like normals are (I already tested bump mapping where tangents was not smooth and it looked correct). The problem I believe is that Pokémon seems to use object space normal mapping (which doesn't need Normal and Tagent in the first place). The type of normal map kind of depends on what the vertex shader feeds to the gpu, the output being just a quaternion representing the normal rotation(?), so my current theory is that the normal map type is vertex shader-dependent and pokemon uses object space. Through it would be weird that the model includes Normal and Tangent when they are not needed. hmm...
