### ISSUE TITLE
Unable to fully compile

### ISSUE THREAD

**Issue by KekMcGee** [gdkchan/SPICA#3]
Visual Studio is only compiling Spica.WinForms.

some warnings it shows as well

1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\NW4C\CMDL.cs(1305,27,1305,34): warning CS0219: The variable 'vertAtt' is assigned but its value is never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\NW4C\CMDL.cs(1306,33,1306,40): warning CS0219: The variable 'streams' is assigned but its value is never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\NW4C\CMDL.cs(1308,27,1308,29): warning CS0168: The variable 'sb' is declared but never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\NW4C\CMDL.cs(1740,31,1740,36): warning CS0168: The variable 'fmeta' is declared but never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\NW4C\CMDL.cs(1741,25,1741,29): warning CS0168: The variable 'fset' is declared but never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DAnimMtxTransform.cs(14,28,14,38): warning CS0649: Field 'H3DAnimMtxTransform.PostRepeat' is never assigned to, and will always have its default value
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DAnimQuatTransform.cs(14,22,14,27): warning CS0649: Field 'H3DAnimQuatTransform.Flags' is never assigned to, and will always have its default value 0
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DAnimMtxTransform.cs(18,32,18,38): warning CS0649: Field 'H3DAnimMtxTransform.Frames' is never assigned to, and will always have its default value null
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Model\Mesh\H3DMesh.cs(59,22,59,40): warning CS0169: The field 'H3DMesh.UserDefinedAddress' is never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Model\H3DBone.cs(20,24,20,31): warning CS0169: The field 'H3DBone.Padding' is never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Model\H3DModel.cs(47,22,47,40): warning CS0169: The field 'H3DModel.UserDefinedAddress' is never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DFloatKeyFrameGroup.cs(28,23,28,34): warning CS0649: Field 'H3DFloatKeyFrameGroup.ValueOffset' is never assigned to, and will always have its default value 0
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DAnimBoolean.cs(10,28,10,37): warning CS0649: Field 'H3DAnimBoolean.PreRepeat' is never assigned to, and will always have its default value
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\LUT\H3DLUTSampler.cs(11,24,11,32): warning CS0169: The field 'H3DLUTSampler.Padding1' is never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Model\Material\Texture\H3DTextureMapper.cs(16,24,16,31): warning CS0169: The field 'H3DTextureMapper.Padding' is never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\H3DHeader.cs(31,22,31,29): warning CS0169: The field 'H3DHeader.Padding' is never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DAnimMtxTransform.cs(10,22,10,32): warning CS0649: Field 'H3DAnimMtxTransform.StartFrame' is never assigned to, and will always have its default value 0
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DFloatKeyFrameGroup.cs(25,24,25,29): warning CS0649: Field 'H3DFloatKeyFrameGroup.Count' is never assigned to, and will always have its default value 0
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DFloatKeyFrameGroup.cs(30,23,30,34): warning CS0169: The field 'H3DFloatKeyFrameGroup.InvDuration' is never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DAnimBoolean.cs(11,28,11,38): warning CS0649: Field 'H3DAnimBoolean.PostRepeat' is never assigned to, and will always have its default value
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DAnimMtxTransform.cs(16,23,16,33): warning CS0649: Field 'H3DAnimMtxTransform.CurveIndex' is never assigned to, and will always have its default value 0
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DAnimMtxTransform.cs(11,22,11,30): warning CS0649: Field 'H3DAnimMtxTransform.EndFrame' is never assigned to, and will always have its default value 0
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DAnimFloat.cs(7,22,7,27): warning CS0169: The field 'H3DAnimFloat.Flags' is never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DFloatKeyFrameGroup.cs(27,23,27,33): warning CS0649: Field 'H3DFloatKeyFrameGroup.ValueScale' is never assigned to, and will always have its default value 0
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Texture\H3DTexture.cs(24,24,24,31): warning CS0169: The field 'H3DTexture.Padding' is never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\H3DHeader.cs(28,20,28,40): warning CS0649: Field 'H3DHeader.UnInitCommandsLength' is never assigned to, and will always have its default value 0
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\H3DVertexData.cs(10,22,10,29): warning CS0169: The field 'H3DVertexData.Padding' is never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DAnimMtxTransform.cs(13,28,13,37): warning CS0649: Field 'H3DAnimMtxTransform.PreRepeat' is never assigned to, and will always have its default value
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Model\Mesh\H3DMesh.cs(21,22,21,29): warning CS0169: The field 'H3DMesh.Padding' is never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\LUT\H3DLUTSampler.cs(10,22,10,30): warning CS0169: The field 'H3DLUTSampler.Padding0' is never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DAnimVector2D.cs(7,22,7,27): warning CS0169: The field 'H3DAnimVector2D.Flags' is never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DAnimTransform.cs(11,22,11,27): warning CS0649: Field 'H3DAnimTransform.Flags' is never assigned to, and will always have its default value 0
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DFloatKeyFrameGroup.cs(23,40,23,59): warning CS0649: Field 'H3DFloatKeyFrameGroup.SegmentQuantization' is never assigned to, and will always have its default value
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Model\Mesh\H3DSubMesh.cs(15,22,15,29): warning CS0169: The field 'H3DSubMesh.Padding' is never used
1>C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA\Formats\CtrH3D\Animation\H3DFloatKeyFrameGroup.cs(29,23,29,33): warning CS0649: Field 'H3DFloatKeyFrameGroup.FrameScale' is never assigned to, and will always have its default value 0
1>  SPICA.WinForms -> C:\Users\KEKERINO\Downloads\SPICA-master\SPICA-master\SPICA.WinForms\bin\Release\SPICA.WinForms.exe

**Comment by gdkchan** [comment]
Those warning are normal, it complains about some unused variables but those variable ARE actually used (through reflection on the serializers), but the compiler have no way to know that. Also it is only supposed to compile one executable, the other projects are shared projects and therefore the code is "embedded" inside the final executable.
