### ISSUE TITLE
Model exporting with reduced polys

### ISSUE THREAD

**Issue by lulzsun** [gdkchan/SPICA#46]
![actrees](https://user-images.githubusercontent.com/28168454/37030536-25d3703c-20f0-11e8-9e73-005a186c7282.png)

Model extracted from Animal Crossing New Leaf.
Model looks fine in SPICA but when exported it seems the polys have been reduced.
I am not that familiar with modeling terms, but I'm assuming it is because the model is technically a billboard model and I think this issue has already been addressed before. 
Any idea on how to properly export this?

**Comment by GiggleX** [comment]
First of all, models are not billboarded. Sprites are. The polycount is fine, it is exported as it is, Set the Rendering mode in Unity (Leaf material) to "Cutout", and it should be mostly fine, Also, set the textures filter to "Point" and enable texture alpha.

**Comment by lulzsun** [comment]
Thank you! I didn't even consider that. It works great now.
