### ISSUE TITLE
Sun & Moon Player color mask data

### ISSUE THREAD

**Issue by froslumugu** [gdkchan/SPICA#6]
Pokemon X&Y Player trainer customization files had mask textures included for applying colors to the base textures, do Sun & Moon also do this? If so, Is/Will SPICA be capable of extracting these masks?

**Comment by gdkchan** [comment]
It doesn't seem to use mask data. I looked the hair model for example, and it contains a constant color on the material that is the hair color. The white hair texture is then multiplied with this constant color and this results on the final color you see on the game. Maybe the body model uses masks through, I will need to take a look. Also yes, if it does contain mask textures then the tool can extract them.

**Comment by froslumugu** [comment]
Hair didn't have mask data in X&Y either, so it is possible that it works the same way in S&M.
Thank you for replying!
