### ISSUE TITLE
Is it possible to import a modified model to a bch file in theory? Why or why not?

### ISSUE THREAD

**Issue by LITTOMA** [gdkchan/SPICA#67]

**Comment by legoj15** [comment]
This tool _wanted_ to have that functionality, but the maintainer/developer left to work on bigger projects. I think Ohana3DS ([Rebirth](https://github.com/gdkchan/Ohana3DS-Rebirth)/[Transfigured](https://github.com/Quibilia/Ohana3DS-Transfigured)) has the ability to import a model and export it as a BCH ability but I've never used it for that.

**Comment by LITTOMA** [comment]
Hi legoj15, thanks for your reply.
I've tested the save bch function of this project. But in the game, the models is failed to load. A lot of data changed in the new bch file. I don't know how they handle the function.

In fact, I'm going to write a tool for importing models. But I have never study on computer graphics. Seems like the bch format is a very complex format. This could be a great challenge for me.

**Comment by gdkchan** [comment]
It can create bch files, but there are several different versions of the bch format out there (they usually have small differences), so I can't guarantee that the tool will be able to properly save all those versions (or even all the sections on a bch file). That said, I believe that a few people has been able to successfully use it to create new ones (see https://github.com/gdkchan/SPICA/issues/41 for example).

**Comment by LITTOMA** [comment]
OK, guys. I got some "untalkable"(maybe) tools which are able to create legit bch files. It's time to close the issue. Thanks for your help.
