### ISSUE TITLE
Windows Build Link Broken

### ISSUE THREAD

**Issue by Erico9002** [gdkchan/SPICA#80]
On following the link, https://ci.appveyor.com/api/projects/gdkchan/spica/artifacts/spica_lastest.zip

Met with following:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:2b8655c6-101e-005d-07fb-9b4ae0000000 Time:2019-11-15T21:24:53.8827469Z
</Message>
</Error>

**Comment by Reisyukaku** [comment]
https://github.com/gdkchan/SPICA/releases/tag/v0.1

**Comment by gdkchan** [comment]
You broke the build with the LZ4 dependency. Please fix it @Reisyukaku.
There's no need for a external dep just for LZ4 decompression, the decompressor is just a few lines of code:
https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.HLE/Loaders/Compression/Lz4.cs

**Comment by Reisyukaku** [comment]
ah, didnt know you had an impl. done.
e099ae4b165b891a3e5fae80d064b637a39f2827
